<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="Plugins\Imaging.Plugins.deps.json" />
        <None Remove="Plugins\Imaging.Plugins.dll" />
        <None Remove="Plugins\Imaging.Plugins.Interface.dll" />
        <None Remove="Plugins\Imazen.WebP.dll" />
        <None Remove="Plugins\runtimes\win-x64\native\libsharpyuv.dll" />
        <None Remove="Plugins\runtimes\win-x64\native\libwebp.dll" />
        <None Remove="Plugins\runtimes\win-x64\native\libwebpdemux.dll" />
        <None Remove="Plugins\runtimes\win-x64\native\libwebpmux.dll" />
        <None Remove="Plugins\runtimes\win\lib\net9.0\Microsoft.Win32.SystemEvents.dll" />
        <None Remove="Plugins\System.Drawing.Common.dll" />
        <None Remove="Plugins\System.Private.Windows.Core.dll" />
        <None Remove="System\green.png" />
        <None Remove="System\red.png" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="Plugins\Imaging.Plugins.deps.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Plugins\Imaging.Plugins.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Plugins\Imaging.Plugins.Interface.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Plugins\Imazen.WebP.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Plugins\runtimes\win-x64\native\libsharpyuv.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Plugins\runtimes\win-x64\native\libwebp.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Plugins\runtimes\win-x64\native\libwebpdemux.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Plugins\runtimes\win-x64\native\libwebpmux.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Plugins\runtimes\win\lib\net9.0\Microsoft.Win32.SystemEvents.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Plugins\System.Drawing.Common.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="Plugins\System.Private.Windows.Core.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="System\green.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <EmbeddedResource Include="System\red.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common.Images\Common.Images.csproj" />
        <ProjectReference Include="..\Imaging\Imaging.csproj" />
        <ProjectReference Include="..\SlimControls\SlimControls.csproj" />
        <ProjectReference Include="..\SlimViews\SlimViews.csproj" />
    </ItemGroup>

</Project>